import '../models/city.dart';
import '../models/crowd_category.dart';
import '../models/place.dart';
import 'mock_data.dart';

class CityData {
  static List<City> getSupportedCities() {
    return const [
      City(
        id: 'varanasi',
        name: 'Varanasi',
        state: 'Uttar Pradesh',
        centerLat: 25.3076,
        centerLng: 83.0105,
        defaultZoom: 14.5,
        tagline: 'Sacred Riverfronts & Aarti Corridors',
        bannerImageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
        hotspotCount: 8,
      ),
      City(
        id: 'delhi',
        name: 'Delhi (NCR)',
        state: 'National Capital Region',
        centerLat: 28.6139,
        centerLng: 77.2090,
        defaultZoom: 13.0,
        tagline: 'Historic Monuments & Bustling Bazaars',
        bannerImageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
        hotspotCount: 6,
      ),
      City(
        id: 'mumbai',
        name: 'Mumbai',
        state: 'Maharashtra',
        centerLat: 18.9438,
        centerLng: 72.8233,
        defaultZoom: 13.0,
        tagline: 'Coastal Promenades & Financial Hubs',
        bannerImageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
        hotspotCount: 6,
      ),
      City(
        id: 'bengaluru',
        name: 'Bengaluru',
        state: 'Karnataka',
        centerLat: 12.9716,
        centerLng: 77.5946,
        defaultZoom: 13.5,
        tagline: 'Lush Tech Parks & Vibrant High Streets',
        bannerImageUrl: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80',
        hotspotCount: 5,
      ),
      City(
        id: 'jaipur',
        name: 'Jaipur',
        state: 'Rajasthan',
        centerLat: 26.9239,
        centerLng: 75.8267,
        defaultZoom: 13.5,
        tagline: 'Royal Palaces & Pink City Bazaars',
        bannerImageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80',
        hotspotCount: 5,
      ),
    ];
  }

  static List<Place> getAllPlaces() {
    final varanasiPlaces = MockData.getPlaces();

    final delhiPlaces = [
      Place(
        id: 'delhi_india_gate',
        name: 'India Gate & Kartavya Path',
        city: 'Delhi (NCR)',
        category: 'Monument',
        latitude: 28.6129,
        longitude: 77.2295,
        description: 'Iconic war memorial and grand ceremonial boulevard, packed with evening families, walkers, and ice cream stalls.',
        address: 'Kartavya Path, India Gate, New Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
        currentScore: 84,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 88,
        distinctSnapCountLastHour: 28,
        communityVotesCount: 52,
        alternativePlaceId: 'delhi_lodhi_gardens',
        alternativePlaceName: 'Lodhi Gardens (Calm & Green)',
        bestTimeToVisit: '06:00 AM - 08:00 AM for sunrise runs',
        liveAlert: 'Heavy visitor rush along central lawns. Traffic slow near C-Hexagon.',
        hourlyForecast: [10, 5, 5, 8, 25, 45, 40, 30, 25, 30, 35, 38, 35, 40, 55, 75, 88, 92, 90, 80, 55, 35, 20, 15],
      ),
      Place(
        id: 'delhi_chandni_chowk',
        name: 'Chandni Chowk & Red Fort',
        city: 'Delhi (NCR)',
        category: 'Market',
        latitude: 28.6562,
        longitude: 77.2410,
        description: 'Vibrant Mughal-era marketplace renowned for street food, spice markets, and grand heritage.',
        address: 'Chandni Chowk, Old Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?w=800&auto=format&fit=crop&q=80',
        currentScore: 91,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 95,
        distinctSnapCountLastHour: 34,
        communityVotesCount: 68,
        alternativePlaceId: 'delhi_lodhi_gardens',
        alternativePlaceName: 'Lodhi Gardens',
        bestTimeToVisit: '10:30 AM - 12:00 PM (Lesser crowd)',
        liveAlert: 'Heavy pedestrian congestion. E-rickshaw restrictions in effect.',
        hourlyForecast: [5, 5, 5, 5, 10, 20, 35, 55, 75, 88, 90, 88, 85, 88, 92, 94, 92, 85, 65, 40, 20, 10, 5, 5],
      ),
      Place(
        id: 'delhi_connaught_place',
        name: 'Connaught Place (Inner Circle)',
        city: 'Delhi (NCR)',
        category: 'Commercial',
        latitude: 28.6315,
        longitude: 77.2167,
        description: 'Georgian-style colonnaded shopping and culinary hub centered around Central Park.',
        address: 'Connaught Place, New Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
        currentScore: 68,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 74,
        distinctSnapCountLastHour: 18,
        communityVotesCount: 39,
        alternativePlaceId: 'delhi_lodhi_gardens',
        bestTimeToVisit: '01:00 PM - 04:00 PM (Weekday lunch)',
        liveAlert: 'Parking in inner circle full. Use underground Palika parking.',
        hourlyForecast: [5, 5, 5, 5, 10, 15, 20, 30, 45, 55, 65, 70, 68, 65, 68, 75, 82, 85, 78, 65, 45, 25, 12, 8],
      ),
      Place(
        id: 'delhi_lodhi_gardens',
        name: 'Lodhi Gardens',
        city: 'Delhi (NCR)',
        category: 'Park',
        latitude: 28.5933,
        longitude: 77.2197,
        description: 'Sprawling 90-acre heritage park housing 15th-century Sayyid and Lodhi architectural tombs. Lush and quiet.',
        address: 'Lodhi Rd, New Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        currentScore: 22,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 20,
        distinctSnapCountLastHour: 4,
        communityVotesCount: 12,
        bestTimeToVisit: '07:00 AM - 10:00 AM or 04:00 PM - 06:00 PM',
        liveAlert: '🟢 Serene & uncrowded. Excellent haven away from metro rush.',
        hourlyForecast: [5, 5, 5, 10, 30, 45, 40, 25, 20, 18, 18, 15, 15, 18, 22, 30, 35, 30, 20, 10, 5, 5, 5, 5],
      ),
      Place(
        id: 'delhi_hauz_khas',
        name: 'Hauz Khas Village & Fort',
        city: 'Delhi (NCR)',
        category: 'Heritage',
        latitude: 28.5535,
        longitude: 77.1944,
        description: 'Medieval reservoir ruins meeting trendy designer boutiques, rooftop bistros, and Deer Park trails.',
        address: 'Hauz Khas Village, New Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        currentScore: 56,
        crowdCategory: CrowdCategory.moderate,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 60,
        distinctSnapCountLastHour: 14,
        communityVotesCount: 28,
        bestTimeToVisit: '03:30 PM - 06:00 PM',
        liveAlert: 'Lake view benches available. Moderate walking traffic.',
        hourlyForecast: [5, 5, 5, 5, 10, 15, 20, 25, 30, 35, 40, 42, 45, 50, 60, 68, 72, 70, 65, 50, 35, 20, 10, 5],
      ),
      Place(
        id: 'delhi_lotus_temple',
        name: 'Lotus Temple (Bahá\'í House)',
        city: 'Delhi (NCR)',
        category: 'Temple',
        latitude: 28.5535,
        longitude: 77.2588,
        description: 'Architectural marvel shaped like an unfolding lotus flower, surrounded by nine ponds and gardens.',
        address: 'Kalkaji, New Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&auto=format&fit=crop&q=80',
        currentScore: 72,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 68,
        distinctSnapCountLastHour: 16,
        communityVotesCount: 31,
        bestTimeToVisit: '09:00 AM - 10:30 AM (Opening queue)',
        liveAlert: 'Visitor line is ~20 mins long. Shoes counter active.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 25, 55, 75, 80, 78, 72, 75, 80, 82, 75, 40, 10, 5, 5, 5, 5, 5],
      ),
    ];

    final mumbaiPlaces = [
      Place(
        id: 'mumbai_gateway',
        name: 'Gateway of India & Colaba',
        city: 'Mumbai',
        category: 'Heritage',
        latitude: 18.9220,
        longitude: 72.8347,
        description: 'Iconic seafront basalt arch overlooking the Arabian Sea and Taj Mahal Palace hotel.',
        address: 'Apollo Bandar, Colaba, Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
        currentScore: 86,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 82,
        distinctSnapCountLastHour: 25,
        communityVotesCount: 48,
        alternativePlaceId: 'mumbai_sanjay_gandhi',
        alternativePlaceName: 'Sanjay Gandhi National Park',
        bestTimeToVisit: '07:00 AM - 08:30 AM (Open breezy plaza)',
        liveAlert: 'Heavy tourist and photography crowd. Elephanta ferry lines long.',
        hourlyForecast: [15, 10, 5, 10, 20, 35, 40, 45, 50, 58, 65, 68, 65, 70, 82, 88, 92, 90, 80, 60, 45, 30, 20, 15],
      ),
      Place(
        id: 'mumbai_marine_drive',
        name: 'Marine Drive Promenade',
        city: 'Mumbai',
        category: 'Promenade',
        latitude: 18.9438,
        longitude: 72.8233,
        description: '3.6 km long arc along Netaji Subhash Chandra Bose Road, beloved for sunset breezes and Queen\'s Necklace lights.',
        address: 'Marine Drive, South Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&auto=format&fit=crop&q=80',
        currentScore: 68,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 70,
        distinctSnapCountLastHour: 21,
        communityVotesCount: 42,
        bestTimeToVisit: '05:30 AM - 07:30 AM or 10:00 PM for night calm',
        liveAlert: 'Seawall seating active. Moving crowd enjoying sunset.',
        hourlyForecast: [20, 15, 10, 10, 25, 50, 45, 30, 25, 28, 30, 32, 30, 35, 48, 65, 78, 85, 82, 75, 60, 45, 35, 25],
      ),
      Place(
        id: 'mumbai_juhu_beach',
        name: 'Juhu Beach Chowpatty',
        city: 'Mumbai',
        category: 'Beach',
        latitude: 19.0988,
        longitude: 72.8264,
        description: 'Vibrant seaside shore famed for pav bhaji stalls, bhel puri, and coastal sunsets.',
        address: 'Juhu Tara Rd, Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        currentScore: 82,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 88,
        distinctSnapCountLastHour: 23,
        communityVotesCount: 45,
        bestTimeToVisit: '06:00 AM - 08:00 AM (Morning joggers)',
        liveAlert: 'Food stall street congested. Slow traffic on Juhu Tara Road.',
        hourlyForecast: [10, 5, 5, 5, 20, 35, 30, 20, 18, 20, 25, 30, 35, 45, 65, 80, 88, 92, 85, 70, 50, 30, 20, 15],
      ),
      Place(
        id: 'mumbai_sanjay_gandhi',
        name: 'Sanjay Gandhi National Park',
        city: 'Mumbai',
        category: 'Nature',
        latitude: 19.2288,
        longitude: 72.9182,
        description: 'Unique protected forest within city limits containing 2000-year-old Kanheri rock-cut caves.',
        address: 'Borivali East, Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        currentScore: 20,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 25,
        distinctSnapCountLastHour: 3,
        communityVotesCount: 11,
        bestTimeToVisit: '08:00 AM - 12:00 PM for peaceful hiking',
        liveAlert: '🟢 Pristine and calm. Low visitor count inside forest trails.',
        hourlyForecast: [5, 5, 5, 5, 10, 25, 35, 30, 25, 22, 20, 20, 18, 18, 22, 28, 25, 15, 5, 5, 5, 5, 5, 5],
      ),
      Place(
        id: 'mumbai_bandstand',
        name: 'Bandra Bandstand & Fort',
        city: 'Mumbai',
        category: 'Promenade',
        latitude: 19.0435,
        longitude: 72.8197,
        description: 'Rocky coastline promenade with sea views, Castella de Aguada fort ruins, and celebrity homes.',
        address: 'Bandstand Promenade, Bandra West, Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        currentScore: 58,
        crowdCategory: CrowdCategory.moderate,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 62,
        distinctSnapCountLastHour: 15,
        communityVotesCount: 30,
        bestTimeToVisit: '04:30 PM - 06:30 PM',
        liveAlert: 'Moderate sea breeze crowd. Walking path open.',
        hourlyForecast: [10, 5, 5, 5, 15, 25, 25, 20, 20, 22, 25, 28, 30, 35, 48, 62, 70, 72, 65, 50, 35, 25, 15, 10],
      ),
      Place(
        id: 'mumbai_dadar_market',
        name: 'Dadar Flower & Vegetable Market',
        city: 'Mumbai',
        category: 'Market',
        latitude: 19.0178,
        longitude: 72.8478,
        description: 'Wholesale flower market bustling before dawn with marigolds, roses, and vendor commerce.',
        address: 'Dadar West, Mumbai',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
        currentScore: 88,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 92,
        distinctSnapCountLastHour: 19,
        communityVotesCount: 40,
        bestTimeToVisit: '04:00 AM - 06:00 AM for fresh wholesale trading',
        liveAlert: 'Narrow aisles heavily packed. Rail bridge approach congested.',
        hourlyForecast: [40, 55, 75, 92, 95, 90, 85, 75, 65, 55, 50, 48, 45, 50, 60, 70, 75, 70, 60, 50, 40, 35, 30, 35],
      ),
    ];

    final bengaluruPlaces = [
      Place(
        id: 'blr_church_street',
        name: 'Church Street & MG Road',
        city: 'Bengaluru',
        category: 'Commercial',
        latitude: 12.9752,
        longitude: 77.6066,
        description: 'Paved pedestrian-friendly strip famous for secondhand bookshops, art cafes, and street musicians.',
        address: 'Church St, Shanthala Nagar, Bengaluru',
        imageUrl: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80',
        currentScore: 78,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 84,
        distinctSnapCountLastHour: 22,
        communityVotesCount: 44,
        alternativePlaceId: 'blr_cubbon_park',
        alternativePlaceName: 'Cubbon Park (Serene Green)',
        bestTimeToVisit: '11:00 AM - 02:00 PM for peaceful cafe reads',
        liveAlert: 'Pedestrian street active. Heavy weekend evening youth crowd.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 25, 40, 55, 65, 70, 68, 65, 70, 78, 85, 88, 85, 75, 55, 30, 15, 8],
      ),
      Place(
        id: 'blr_cubbon_park',
        name: 'Cubbon Park',
        city: 'Bengaluru',
        category: 'Park',
        latitude: 12.9767,
        longitude: 77.5928,
        description: '300-acre lush green lung in the heart of Bengaluru with bamboo groves, bandstand, and library.',
        address: 'Kasturba Rd, Sampangi Rama Nagar, Bengaluru',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        currentScore: 24,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 28,
        distinctSnapCountLastHour: 5,
        communityVotesCount: 14,
        bestTimeToVisit: '06:00 AM - 09:00 AM (Quiet birdwatching)',
        liveAlert: '🟢 Peaceful & breezy. Open lawns and shady walking paths.',
        hourlyForecast: [5, 5, 5, 15, 35, 50, 45, 30, 25, 20, 18, 18, 18, 20, 25, 32, 35, 30, 20, 10, 5, 5, 5, 5],
      ),
      Place(
        id: 'blr_koramangala',
        name: 'Koramangala 80ft Road',
        city: 'Bengaluru',
        category: 'Commercial',
        latitude: 12.9352,
        longitude: 77.6245,
        description: 'Bustling avenue packed with startup hubs, specialty coffee roasters, and microbreweries.',
        address: '80 Feet Rd, Koramangala 4th Block, Bengaluru',
        imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
        currentScore: 72,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 80,
        distinctSnapCountLastHour: 17,
        communityVotesCount: 36,
        bestTimeToVisit: '02:00 PM - 05:00 PM (Coworking lull)',
        liveAlert: 'Traffic slow near Sony World junction. Valet lines at restaurants.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 25, 45, 60, 68, 72, 70, 68, 72, 78, 85, 88, 86, 78, 60, 35, 18, 10],
      ),
      Place(
        id: 'blr_commercial_st',
        name: 'Commercial Street',
        city: 'Bengaluru',
        category: 'Market',
        latitude: 12.9822,
        longitude: 77.6083,
        description: 'Famous historic retail labyrinth for fashion, silk, footwear, and bridal wear.',
        address: 'Tasker Town, Shivaji Nagar, Bengaluru',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
        currentScore: 82,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 86,
        distinctSnapCountLastHour: 19,
        communityVotesCount: 42,
        alternativePlaceId: 'blr_cubbon_park',
        bestTimeToVisit: '11:00 AM - 01:30 PM (Stores opening)',
        liveAlert: 'Heavy shopper density in lane intersections.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 30, 50, 68, 75, 78, 75, 78, 85, 90, 88, 82, 70, 45, 20, 10, 5, 5],
      ),
      Place(
        id: 'blr_lalbagh',
        name: 'Lalbagh Botanical Garden',
        city: 'Bengaluru',
        category: 'Park',
        latitude: 12.9507,
        longitude: 77.5848,
        description: 'Historic 240-acre garden commissioned by Hyder Ali, featuring the iconic Victorian Glass House and ancient rock.',
        address: 'Mavalli, Bengaluru',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        currentScore: 32,
        crowdCategory: CrowdCategory.moderate,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 35,
        distinctSnapCountLastHour: 8,
        communityVotesCount: 20,
        bestTimeToVisit: '06:30 AM - 09:00 AM (Lake morning walk)',
        liveAlert: 'Pleasant flow. Easy parking near West Gate.',
        hourlyForecast: [5, 5, 5, 10, 30, 45, 40, 30, 25, 22, 20, 20, 22, 25, 32, 40, 38, 30, 15, 10, 5, 5, 5, 5],
      ),
    ];

    final jaipurPlaces = [
      Place(
        id: 'jaipur_hawa_mahal',
        name: 'Hawa Mahal & Badi Chaupar',
        city: 'Jaipur',
        category: 'Heritage',
        latitude: 26.9239,
        longitude: 75.8267,
        description: 'The 5-story pink sandstone Palace of Winds with 953 ornate jharokhas windows.',
        address: 'Hawa Mahal Rd, Badi Choupad, Jaipur',
        imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80',
        currentScore: 82,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 85,
        distinctSnapCountLastHour: 24,
        communityVotesCount: 46,
        alternativePlaceId: 'jaipur_sisodia',
        alternativePlaceName: 'Sisodia Rani Garden',
        bestTimeToVisit: '07:30 AM - 09:00 AM (Sunlight on front facade)',
        liveAlert: 'Photo viewpoints crowded across the street. Slow traffic on main road.',
        hourlyForecast: [5, 5, 5, 5, 10, 20, 35, 55, 75, 85, 88, 85, 80, 82, 88, 90, 85, 75, 55, 35, 18, 10, 5, 5],
      ),
      Place(
        id: 'jaipur_amer_fort',
        name: 'Amer Fort & Maota Lake',
        city: 'Jaipur',
        category: 'Fort',
        latitude: 26.9855,
        longitude: 75.8513,
        description: 'Majestic hilltop fort crafted from red sandstone and marble, overlooking reflection lake.',
        address: 'Devisinghpura, Amer, Jaipur',
        imageUrl: 'https://images.unsplash.com/photo-1609137144822-26159c934335?w=800&auto=format&fit=crop&q=80',
        currentScore: 76,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 78,
        distinctSnapCountLastHour: 19,
        communityVotesCount: 38,
        bestTimeToVisit: '08:00 AM - 10:00 AM (Cool morning climb)',
        liveAlert: 'Courtyard queue moving steadily. Elephant path busy.',
        hourlyForecast: [5, 5, 5, 5, 5, 15, 30, 50, 75, 85, 88, 85, 82, 80, 82, 85, 78, 60, 35, 15, 10, 5, 5, 5],
      ),
      Place(
        id: 'jaipur_nahargarh',
        name: 'Nahargarh Fort (Sunset Point)',
        city: 'Jaipur',
        category: 'Viewpoint',
        latitude: 26.9372,
        longitude: 75.8155,
        description: 'Perched along the Aravalli ridge, the ultimate viewpoint overlooking the entire illuminated Pink City.',
        address: 'Krishna Nagar, Brahampuri, Jaipur',
        imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
        currentScore: 88,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 90,
        distinctSnapCountLastHour: 27,
        communityVotesCount: 51,
        bestTimeToVisit: '03:00 PM - 04:30 PM (Arrive early before sunset bottleneck)',
        liveAlert: 'Ghat road leading up to fort has heavy vehicle queue.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 20, 25, 30, 35, 38, 40, 45, 60, 80, 92, 95, 88, 70, 45, 25, 10, 5],
      ),
      Place(
        id: 'jaipur_johari_bazaar',
        name: 'Johari Bazaar',
        city: 'Jaipur',
        category: 'Market',
        latitude: 26.9197,
        longitude: 75.8261,
        description: 'Historic walled city bazaar acclaimed for authentic Kundan jewelry, tie-dye bandhani textiles, and street sweets.',
        address: 'Johari Bazar, Pink City, Jaipur',
        imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
        currentScore: 74,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 80,
        distinctSnapCountLastHour: 15,
        communityVotesCount: 33,
        bestTimeToVisit: '11:30 AM - 02:00 PM',
        liveAlert: 'High pedestrian movement under pink colonnades.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 15, 25, 45, 65, 75, 78, 72, 75, 80, 85, 82, 78, 65, 45, 20, 10, 5, 5],
      ),
      Place(
        id: 'jaipur_sisodia',
        name: 'Sisodia Rani Garden & Palace',
        city: 'Jaipur',
        category: 'Garden',
        latitude: 26.8820,
        longitude: 75.8562,
        description: 'Terraced Mughal-style garden with painted pavilions depicting Radha-Krishna murals and tranquil water fountains.',
        address: 'Agra Rd, Ghat Ki Guni, Jaipur',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        currentScore: 19,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 22,
        distinctSnapCountLastHour: 3,
        communityVotesCount: 8,
        bestTimeToVisit: '09:00 AM - 11:30 AM or 04:00 PM - 06:00 PM',
        liveAlert: '🟢 Serene and picturesque. Perfect calm alternative to city crowds.',
        hourlyForecast: [5, 5, 5, 5, 5, 10, 18, 22, 20, 18, 16, 16, 15, 18, 22, 28, 25, 20, 10, 5, 5, 5, 5, 5],
      ),
    ];

    return [
      ...varanasiPlaces,
      ...delhiPlaces,
      ...mumbaiPlaces,
      ...bengaluruPlaces,
      ...jaipurPlaces,
    ];
  }
}
