import 'package:flutter/material.dart';
import '../models/crowd_category.dart';
import '../models/place.dart';
import '../models/snap.dart';
import '../models/user_profile.dart';
import '../models/vibe_ping.dart';

class MockData {
  static List<Place> getPlaces() {
    return [
      Place(
        id: 'dashashwamedh_ghat',
        name: 'Dashashwamedh Ghat',
        category: 'Ghat',
        latitude: 25.3076,
        longitude: 25.3076 > 80 ? 83.0105 : 83.0105,
        description: 'The world-famous heart of Varanasi riverfront, known for the magnificent evening Ganga Aarti.',
        address: 'Dashashwamedh Ghat Rd, Bangali Tola, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
        currentScore: 88,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.avoid,
        approachTrafficScore: 92,
        distinctSnapCountLastHour: 24,
        communityVotesCount: 47,
        alternativePlaceId: 'chet_singh_ghat',
        alternativePlaceName: 'Chet Singh Ghat (Calm & Serene)',
        bestTimeToVisit: 'Early Morning 05:30 - 07:00 AM or Late Night after 09:15 PM',
        liveAlert: '🔥 Evening Aarti rush is at peak! Stairs packed, heavy boat congestion.',
        hourlyForecast: [15, 10, 8, 12, 35, 60, 55, 45, 40, 48, 52, 50, 45, 40, 48, 62, 78, 92, 95, 88, 70, 45, 30, 20],
      ),
      Place(
        id: 'assi_ghat',
        name: 'Assi Ghat',
        category: 'Ghat',
        latitude: 25.2903,
        longitude: 83.0062,
        description: 'Southernmost major ghat famous for Subah-e-Banaras morning music, yoga, and lively youth culture.',
        address: 'Assi Ghat, Shivala, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=800&auto=format&fit=crop&q=80',
        currentScore: 58,
        crowdCategory: CrowdCategory.moderate,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 55,
        distinctSnapCountLastHour: 15,
        communityVotesCount: 32,
        alternativePlaceId: 'chet_singh_ghat',
        alternativePlaceName: 'Chet Singh Ghat',
        bestTimeToVisit: '05:00 AM - 07:30 AM (Subah-e-Banaras)',
        liveAlert: 'Chai stalls active, open seating available along the river steps.',
        hourlyForecast: [10, 8, 5, 15, 65, 80, 75, 50, 40, 42, 45, 45, 38, 35, 42, 55, 68, 72, 65, 60, 50, 35, 22, 14],
      ),
      Place(
        id: 'kashi_vishwanath',
        name: 'Kashi Vishwanath Corridor',
        category: 'Temple',
        latitude: 25.3109,
        longitude: 83.0107,
        description: 'Magnificent grand corridor connecting the sacred Jyotirlinga shrine directly to the holy Ganga.',
        address: 'Lahori Tola, Varanasi, Uttar Pradesh 221001',
        imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?w=800&auto=format&fit=crop&q=80',
        currentScore: 82,
        crowdCategory: CrowdCategory.overloaded,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 85,
        distinctSnapCountLastHour: 19,
        communityVotesCount: 54,
        alternativePlaceId: 'panchganga_ghat',
        alternativePlaceName: 'Panchganga Ghat',
        bestTimeToVisit: '12:30 PM - 03:00 PM (Lesser queue time)',
        liveAlert: 'Queue at Gate No. 4 is ~45 mins long. Security checking active.',
        hourlyForecast: [20, 15, 10, 25, 70, 88, 90, 85, 78, 72, 65, 55, 50, 52, 60, 75, 85, 88, 82, 75, 55, 40, 30, 25],
      ),
      Place(
        id: 'godowlia_chowk',
        name: 'Godowlia Crossing & Market',
        category: 'Market',
        latitude: 25.3101,
        longitude: 83.0039,
        description: 'Vibrant nerve center of old Varanasi, famed for Banarasi silk saree showrooms, street sweets, and paan.',
        address: 'Godowlia, Dashaswamedh, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
        currentScore: 78,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.caution,
        approachTrafficScore: 90,
        distinctSnapCountLastHour: 12,
        communityVotesCount: 29,
        alternativePlaceId: 'chet_singh_ghat',
        alternativePlaceName: 'Chet Singh Ghat',
        bestTimeToVisit: '11:00 AM - 02:00 PM',
        liveAlert: 'E-rickshaws restricted on main road. Pedestrian movement heavy.',
        hourlyForecast: [5, 5, 5, 8, 15, 25, 35, 50, 65, 75, 78, 76, 70, 68, 72, 80, 88, 92, 90, 82, 60, 40, 20, 10],
      ),
      Place(
        id: 'chet_singh_ghat',
        name: 'Chet Singh Ghat',
        category: 'Heritage',
        latitude: 25.2965,
        longitude: 83.0055,
        description: 'Historic fortified stone palace ghat from Maharaja Chet Singh era. Incredibly tranquil and picturesque.',
        address: 'Shivala Ghat, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        currentScore: 22,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 25,
        distinctSnapCountLastHour: 3,
        communityVotesCount: 9,
        alternativePlaceId: null,
        bestTimeToVisit: 'Sunset 04:30 PM - 06:30 PM (Ideal for photography)',
        liveAlert: '🟢 Peaceful & breezy. Excellent quiet alternative to crowded central ghats.',
        hourlyForecast: [5, 5, 5, 5, 12, 20, 25, 20, 18, 20, 22, 20, 18, 15, 20, 28, 32, 35, 30, 25, 18, 12, 8, 5],
      ),
      Place(
        id: 'manikarnika_ghat',
        name: 'Manikarnika Ghat',
        category: 'Ghat',
        latitude: 25.3108,
        longitude: 83.0142,
        description: 'The ancient sacred Mahashamshana ghat with an eternal burning flame, profound spiritual significance.',
        address: 'Manikarnika Ghat, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?w=800&auto=format&fit=crop&q=80',
        currentScore: 64,
        crowdCategory: CrowdCategory.bustling,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 60,
        distinctSnapCountLastHour: 7,
        communityVotesCount: 18,
        bestTimeToVisit: 'Early morning via river boat',
        liveAlert: 'High foot movement in narrow approach alleys. Photography restricted near pyres.',
        hourlyForecast: [30, 25, 20, 25, 40, 50, 60, 65, 68, 70, 68, 65, 60, 62, 65, 70, 75, 72, 68, 60, 50, 45, 38, 32],
      ),
      Place(
        id: 'panchganga_ghat',
        name: 'Panchganga Ghat',
        category: 'Heritage',
        latitude: 25.3168,
        longitude: 83.0175,
        description: 'Meeting point of five sacred rivers according to myth. Towering stone stairs and Alamgir Mosque.',
        address: 'Bahu Bazar, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        currentScore: 18,
        crowdCategory: CrowdCategory.calm,
        advisoryVerdict: AdvisoryVerdict.goNow,
        approachTrafficScore: 20,
        distinctSnapCountLastHour: 2,
        communityVotesCount: 6,
        bestTimeToVisit: '04:00 PM - 07:00 PM for river panorama',
        liveAlert: '🟢 Ultra calm. Perfect place for reading, meditation, and quiet boat views.',
        hourlyForecast: [5, 5, 5, 5, 10, 18, 22, 18, 15, 16, 18, 16, 14, 12, 15, 22, 25, 24, 20, 18, 12, 10, 8, 5],
      ),
      Place(
        id: 'namo_ghat',
        name: 'Namo Ghat (Khidkiya Ghat)',
        category: 'Ghat',
        latitude: 25.3347,
        longitude: 83.0368,
        description: 'Spectacular modern riverfront with giant Namaste metal sculptures, promenade, CNG boat station, and cafes.',
        address: 'Rajghat, Varanasi',
        imageUrl: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&auto=format&fit=crop&q=80',
        currentScore: 42,
        crowdCategory: CrowdCategory.moderate,
        advisoryVerdict: AdvisoryVerdict.goodToGo,
        approachTrafficScore: 35,
        distinctSnapCountLastHour: 11,
        communityVotesCount: 22,
        bestTimeToVisit: '05:30 PM - 08:00 PM (Illuminated sculptures)',
        liveAlert: 'Spacious walking space. Food court and open parking available.',
        hourlyForecast: [5, 5, 5, 5, 15, 30, 35, 25, 20, 22, 25, 25, 20, 22, 30, 45, 55, 65, 60, 50, 38, 22, 12, 8],
      ),
    ];
  }

  static List<Snap> getInitialSnaps() {
    final now = DateTime.now();
    return [
      Snap(
        id: 'snap_1',
        placeId: 'dashashwamedh_ghat',
        placeName: 'Dashashwamedh Ghat',
        userId: 'user_priya',
        userName: 'Priya Pandey',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        userRank: 'Varanasi Legend',
        imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 8)),
        caption: 'Aarti preparations in full swing! Stairs are packed all the way up to the top.',
        crowdRating: 4,
        vibeTag: '🪔 Aarti Rush',
        upvotes: 24,
      ),
      Snap(
        id: 'snap_2',
        placeId: 'dashashwamedh_ghat',
        placeName: 'Dashashwamedh Ghat',
        userId: 'user_karan',
        userName: 'Karan Malhotra',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        userRank: 'City Insider',
        imageUrl: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 19)),
        caption: 'Boats lining up 5 rows deep in the river. Huge crowd tonight!',
        crowdRating: 4,
        vibeTag: '🚤 Boat Congestion',
        upvotes: 18,
      ),
      Snap(
        id: 'snap_3',
        placeId: 'assi_ghat',
        placeName: 'Assi Ghat',
        userId: 'user_rohit',
        userName: 'Rohit Verma',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        userRank: 'Pulse Ambassador',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 14)),
        caption: 'Pleasant evening breeze at Assi. Plenty of open steps and lemon chai is flowing!',
        crowdRating: 2,
        vibeTag: '☕ Evening Chai & Vibe',
        upvotes: 31,
      ),
      Snap(
        id: 'snap_4',
        placeId: 'chet_singh_ghat',
        placeName: 'Chet Singh Ghat',
        userId: 'user_ananya',
        userName: 'Ananya Roy',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        userRank: 'Local Scout',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 25)),
        caption: 'Totally calm and surreal here while Dashashwamedh is overflowing. Super chill spot!',
        crowdRating: 1,
        vibeTag: '🌅 Serene Sunset',
        upvotes: 42,
      ),
      Snap(
        id: 'snap_5',
        placeId: 'kashi_vishwanath',
        placeName: 'Kashi Vishwanath Corridor',
        userId: 'user_vikas',
        userName: 'Vikas Tiwari',
        userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
        userRank: 'City Insider',
        imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 32)),
        caption: 'Queue moving steadily now, about 25 minutes from Gate 4 to inner sanctum.',
        crowdRating: 3,
        vibeTag: '🕉️ Darshan Queue',
        upvotes: 19,
      ),
      Snap(
        id: 'snap_6',
        placeId: 'godowlia_chowk',
        placeName: 'Godowlia Crossing',
        userId: 'user_sneha',
        userName: 'Sneha Patel',
        userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
        userRank: 'Local Scout',
        imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80',
        timestamp: now.subtract(const Duration(minutes: 41)),
        caption: 'Godowlia market is jam packed with shoppers and rickshaws. Walk if you can!',
        crowdRating: 4,
        vibeTag: '🛍️ Market Jam',
        upvotes: 15,
      ),
    ];
  }

  static UserProfile getInitialUser() {
    return UserProfile(
      id: 'current_user',
      name: 'Aryan Sharma',
      handle: '@aryanscout',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
      xp: 850,
      streakDays: 5,
      totalSnapsCount: 14,
      totalVerificationsCount: 28,
      cityRank: 4,
      badges: const [
        ScoutBadge(
          id: 'b_first_snap',
          title: 'First Pulse',
          description: 'Contributed your first crowd snap',
          icon: Icons.camera_alt_rounded,
          color: Color(0xFF00E676),
          isUnlocked: true,
          dateEarned: 'Aug 28',
        ),
        ScoutBadge(
          id: 'b_ghat_walker',
          title: 'Ghat Walker',
          description: 'Snapped at 5 distinct Varanasi ghats',
          icon: Icons.directions_walk_rounded,
          color: Color(0xFF2979FF),
          isUnlocked: true,
          dateEarned: 'Sep 02',
        ),
        ScoutBadge(
          id: 'b_vibe_master',
          title: 'Vibe Verifier',
          description: 'Confirmed 25 crowd statuses accurately',
          icon: Icons.verified_rounded,
          color: Color(0xFFFFD600),
          isUnlocked: true,
          dateEarned: 'Yesterday',
        ),
        ScoutBadge(
          id: 'b_aarti_specialist',
          title: 'Aarti Chronicler',
          description: 'Reported during evening peak rush',
          icon: Icons.local_fire_department_rounded,
          color: Color(0xFFFF6D00),
          isUnlocked: false,
        ),
        ScoutBadge(
          id: 'b_legend',
          title: 'Varanasi Legend',
          description: 'Reach 3,000 XP and rank in the City Top 3',
          icon: Icons.military_tech_rounded,
          color: Color(0xFFFF1744),
          isUnlocked: false,
        ),
      ],
      quests: [
        DailyQuest(
          id: 'q1',
          title: 'Share Live Vibe Snap',
          description: 'Post 1 photo snap with crowd rating at any ghat',
          xpReward: 50,
          currentProgress: 0,
          targetProgress: 1,
        ),
        DailyQuest(
          id: 'q2',
          title: 'Vibe Check 2 Hotspots',
          description: 'Confirm or vote on real-time crowd status',
          xpReward: 30,
          currentProgress: 1,
          targetProgress: 2,
        ),
        DailyQuest(
          id: 'q3',
          title: 'Quiet Scout',
          description: 'Spot and report a Calm category haven',
          xpReward: 40,
          currentProgress: 0,
          targetProgress: 1,
        ),
      ],
    );
  }

  static List<Map<String, dynamic>> getLeaderboard() {
    return [
      {
        'rank': 1,
        'name': 'Priya Pandey',
        'handle': '@priyavns',
        'avatar': 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        'xp': 3420,
        'snaps': 84,
        'tier': 'Varanasi Legend',
        'badge': '🏆 Top Scout',
      },
      {
        'rank': 2,
        'name': 'Rohit Verma',
        'handle': '@rohitghats',
        'avatar': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        'xp': 2890,
        'snaps': 62,
        'tier': 'Pulse Ambassador',
        'badge': '🔥 Streak King (18d)',
      },
      {
        'rank': 3,
        'name': 'Devika Sen',
        'handle': '@devikabanaras',
        'avatar': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        'xp': 2150,
        'snaps': 49,
        'tier': 'Pulse Ambassador',
        'badge': '⭐ Aarti Pro',
      },
      {
        'rank': 4,
        'name': 'Aryan Sharma (You)',
        'handle': '@aryanscout',
        'avatar': 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
        'xp': 850,
        'snaps': 14,
        'tier': 'City Insider',
        'badge': '⚡ Rising Scout',
      },
      {
        'rank': 5,
        'name': 'Karan Malhotra',
        'handle': '@karan_kashi',
        'avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        'xp': 790,
        'snaps': 18,
        'tier': 'City Insider',
        'badge': '🚶 Ghat Explorer',
      },
      {
        'rank': 6,
        'name': 'Sneha Patel',
        'handle': '@snehap',
        'avatar': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
        'xp': 640,
        'snaps': 12,
        'tier': 'City Insider',
        'badge': '🎯 Spotter',
      },
    ];
  }

  static List<VibePing> getVibePings() {
    final now = DateTime.now();
    return [
      VibePing(
        id: 'ping_1',
        placeId: 'dashashwamedh_ghat',
        placeName: 'Dashashwamedh Ghat',
        requesterName: 'Meera K.',
        question: 'Are wooden row boats still available near the main steps or booked out?',
        timestamp: now.subtract(const Duration(minutes: 12)),
        answers: [
          VibeAnswer(
            id: 'ans_1',
            responderName: 'Priya Pandey',
            responderRank: 'Varanasi Legend',
            crowdStatus: 'Very Packed',
            comment: 'Front boats are totally full. Walk 200m towards Munshi Ghat for open row boats!',
            timestamp: now.subtract(const Duration(minutes: 6)),
          ),
        ],
      ),
      VibePing(
        id: 'ping_2',
        placeId: 'kashi_vishwanath',
        placeName: 'Kashi Vishwanath Corridor',
        requesterName: 'Amit Saxena',
        question: 'Is locker storage available at Gate 4 or is there a huge line?',
        timestamp: now.subtract(const Duration(minutes: 28)),
        answers: [
          VibeAnswer(
            id: 'ans_2',
            responderName: 'Vikas Tiwari',
            responderRank: 'City Insider',
            crowdStatus: 'Moderate',
            comment: 'Locker queue is about 5 mins right now. Moving fast!',
            timestamp: now.subtract(const Duration(minutes: 20)),
          ),
        ],
      ),
    ];
  }
}
